# Generated by Django 4.2 on 2023-05-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
