# Generated by Django 4.2 on 2023-05-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('company_id', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('logo_size', models.CharField(blank=True, max_length=255, null=True)),
                ('qrcode_color', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'QrCodes',
                'db_table': 'qrcode',
            },
        ),
    ]
