# Generated by Django 4.2 on 2023-05-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_qrcode_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
