# Generated by Django 4.2 on 2023-05-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_qrcode_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='qrcode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
